name: Build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build jar
        run: gradle bootJar
      - name: Copy jar
        run: mv build/libs/server.jar docker
      - name: Build docker image
        run: docker build -t docker.pkg.github.com/honzatrtik/url-checker-server/server:$GITHUB_SHA ./docker
      - name: Push docker image
        run: docker push docker.pkg.github.com/honzatrtik/url-checker-server/server:$GITHUB_SHA